### ISSUE TITLE
Cannot make it to work at all

### ISSUE THREAD

**Issue by StannieV** [anthonychu/functions-headless-chromium#3]
Greetings,

I've tried multiple times to get the Puppeteer demo to work but every time it produces an error when I invoke the URL. Error:

Exception while executing function: Functions.screenshot Result: Failure
Exception: Worker was unable to load function screenshot: 'Error: Cannot find module 'puppeteer'
Require stack:
- /home/site/wwwroot/screenshot/index.js
- /azure-functions-host/workers/node/worker-bundle.js
- /azure-functions-host/workers/node/dist/src/nodejsWorker.js'
Stack: Error: Cannot find module 'puppeteer'
Require stack:
- /home/site/wwwroot/screenshot/index.js
- /azure-functions-host/workers/node/worker-bundle.js
- /azure-functions-host/workers/node/dist/src/nodejsWorker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/site/wwwroot/screenshot/index.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) 

I downloaded the source code, opened the folder puppeteer in Visual Studio Code, Installed puppeteer locally (npm install puppeteer), Deployed it with different variations:

- App Service Plan (B1) & Consumption Plan
- West Europe & Central US
- Node.js 10 & Node.js12

I tried the '--no-sandbox' from issue: Not working with an app service plan #1 

Locally (debugging) it works fine, but in Azure I cannot make it work. I'm a bit lost here... Could you please help me? What is it that I'm doing wrong?

The output from Visual Studio Code:

22:32:25: Creating resource group "puppeteer05" in location "westeurope"...
22:32:26: Successfully created resource group "puppeteer05".
22:32:26: Ensuring App Service plan "puppeteer05" exists...
22:32:26: Creating App Service plan "puppeteer05"...
22:32:39: Successfully created App Service plan "puppeteer05".
22:32:39: Creating storage account "puppeteer05" in location "westeurope" with sku "Standard_LRS"...
22:33:11: Successfully created storage account "puppeteer05".
22:33:11: Verifying that Application Insights is available for this location...
22:33:11: Creating Application Insights resource "puppeteer05"...
22:33:15: Successfully created Application Insights resource "puppeteer05".
22:33:15: Creating new function app "puppeteer05"...
22:33:35: Successfully created function app "puppeteer05": https://puppeteer05.azurewebsites.net
22:33:37 puppeteer05: Starting deployment...
22:33:38 puppeteer05: Creating zip package...
22:33:38 puppeteer05: Zip package size: 6.66 kB
22:34:26 puppeteer05: Fetching changes.
22:34:26 puppeteer05: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/94cc5349-abbf-4491-b1fc-07617c6f2f28.zip (0.01 MB) to /tmp/zipdeploy/extracted
22:34:29 puppeteer05: Updating submodules.
22:34:29 puppeteer05: Preparing deployment for commit id '15b83003cb'.
22:34:30 puppeteer05: Generating deployment script.
22:34:30 puppeteer05: Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"'.
22:34:30 puppeteer05: Generating deployment script for Web Site
22:34:30 puppeteer05: Generated deployment script files
22:34:31 puppeteer05: Running deployment command...
22:34:31 puppeteer05: Command: "/home/site/deployments/tools/deploy.sh"
22:34:31 puppeteer05: Handling Basic Web Site deployment.
22:34:32 puppeteer05: Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
22:34:32 puppeteer05: Copying file: '.funcignore'
22:34:32 puppeteer05: Copying file: 'host.json'
22:34:32 puppeteer05: Copying file: 'package-lock.json'
22:34:32 puppeteer05: Copying file: 'package.json'
22:34:32 puppeteer05: Copying file: 'screenshot/function.json'
22:34:32 puppeteer05: Copying file: 'screenshot/index.js'
22:34:32 puppeteer05: Finished successfully.
22:34:32 puppeteer05: Running post deployment command(s)...
22:34:32 puppeteer05: Triggering recycle (preview mode disabled).
22:34:32 puppeteer05: Deployment successful.
22:34:49 puppeteer05: Syncing triggers...
22:35:45 puppeteer05: Syncing triggers (Attempt 2/6)...
22:36:45 puppeteer05: Syncing triggers (Attempt 3/6)...
22:37:56 puppeteer05: Syncing triggers (Attempt 4/6)...
22:39:26 puppeteer05: Syncing triggers (Attempt 5/6)...
22:39:27 puppeteer05: Querying triggers...
22:39:30 puppeteer05: HTTP Trigger Urls:
  screenshot: https://puppeteer05.azurewebsites.net/api/screenshot

**Comment by aaquibdilkash** [comment]
Hey @StannieV , did you tried installing poppeteer using  "npm i --save puppeteer" in node terminal? maybe it'll work.

**Comment by nagaozen** [comment]
From my experience, deploying from VS Code won't work. You need to use CLI with `--build remote`. Even with `"azureFunctions.scmDoBuildDuringDeployment": true`. Its working for me.

**Comment by StannieV** [comment]
Thanks for the ideas, I'll try them when I have time and let you know the result.

**Comment by StannieV** [comment]
@aaquibdilkash Thanks for your tip, installing puppeteer on the node (I used Bash of the 'Advanced Tools') made it work!

**Comment by StannieV** [comment]
I got it working with deploying it with VS code by using:

settings.json
```
{
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.postDeployTask": "npm install",
    "azureFunctions.projectLanguage": "JavaScript",
    "azureFunctions.projectRuntime": "~3",
    "debug.internalConsoleOptions": "neverOpen",
    "azureFunctions.scmDoBuildDuringDeployment": true,
    "azureFunctions.preDeployTask": "npm prune"
}
```

And

index.js:
```
const puppeteer = require("puppeteer");

module.exports = async function (context, req) {
    const url = req.query.url || "https://google.com/";
    const browser = await puppeteer.launch({
        args: ['--no-sandbox']
    });
    const page = await browser.newPage();
    await page.goto(url);
    const screenshotBuffer = await page.screenshot({ fullPage: true });
    await browser.close();

    context.res = {
        body: screenshotBuffer,
        headers: {
            "content-type": "image/png"
        }
    };
};
```

I did have to deploy twice. The first time, when all the resources are created, there was an error: 'Deployment failed.'. So I redeployed it in the same FunctionApp.

Deployment steps:

1. Get Source code from GIT
2. Open puppeteer folder from source in Visual Studio Code (Folder: ..\functions-headless-chromium\puppeteer)
3. Install the needed plugins (VS Code will ask for them, nothing special to do)
4. Change files mentioned above
5. Open the Azure plugin
6. Press the lightly blue arrow in the Azure plugin window (Info label: Deploy to Function App...)
7. Select your subscription
8. Select: 'Create new Function App in Azure... Advanced'
9. Define a name
10. Select 'Node.js 12' as runtime stack
11. Select 'Linux' as OS
12. Select 'App Service Plan' as hosting plan
13. Select 'Create new App Service plan' as Linux App Service plan
14. Specify App Service plan name
15. Select 'B1' (B1 or higher because they support 64bit)  pricing tier
16. Select 'Create new resource group' as resource group (Windows and Linux cannot be mixed)
17. Specify resource group name
18. Select 'Create new storage account' as storage account (could be existing one)
19. Specify storage account name
20. Select 'Create new Application Insights resource' as Application Insights resource (could be existing one)
21. Specify Application Insights resource name
22. Select location (For example, West Europe)
**After this, the deployment starts!**

Logging:

23:05:54: Creating resource group "puppeteer07" in location "westeurope"...
23:05:55: Successfully created resource group "puppeteer07".
23:05:55: Ensuring App Service plan "puppeteer07" exists...
23:05:55: Creating App Service plan "puppeteer07"...
23:06:01: Successfully created App Service plan "puppeteer07".
23:06:01: Creating storage account "puppeteer07" in location "westeurope" with sku "Standard_LRS"...
23:06:33: Successfully created storage account "puppeteer07".
23:06:33: Verifying that Application Insights is available for this location...
23:06:33: Creating Application Insights resource "puppeteer07"...
23:06:37: Successfully created Application Insights resource "puppeteer07".
23:06:37: Creating new function app "puppeteer07"...
23:06:57: Successfully created function app "puppeteer07": https://puppeteer07.azurewebsites.net
23:07:00 puppeteer07: Starting deployment...
23:07:02 puppeteer07: Creating zip package...
23:07:02 puppeteer07: Zip package size: 6.57 kB
23:08:23 puppeteer07: Fetching changes.
23:08:23 puppeteer07: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/58d89fbb-dc9e-48a0-8c60-7620c7f7e33f.zip (0.01 MB) to /tmp/zipdeploy/extracted
23:08:38 puppeteer07: Deployment failed.
23:09:21 puppeteer07: Starting deployment...
23:09:21 puppeteer07: Creating zip package...
23:09:21 puppeteer07: Zip package size: 6.57 kB
23:09:24 puppeteer07: Fetching changes.
23:09:25 puppeteer07: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/70cbed6c-5b0e-45c2-82ea-ff662db51945.zip (0.01 MB) to /tmp/zipdeploy/extracted
23:09:27 puppeteer07: Updating submodules.
23:09:27 puppeteer07: Preparing deployment for commit id '1b8f4278c5'.
23:09:28 puppeteer07: Repository path is /tmp/zipdeploy/extracted
23:09:28 puppeteer07: Running oryx build...
23:09:28 puppeteer07: Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform nodejs --platform-version ~12 -i /tmp/8d86b0546c187dd
23:09:39 puppeteer07: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
23:09:39 puppeteer07: You can report issues at https://github.com/Microsoft/Oryx/issues
23:09:39 puppeteer07: Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1
23:09:39 puppeteer07: Build Operation ID: |rU8socd5W8E=.22191afd_
23:09:39 puppeteer07: Repository Commit : 1b8f4278c56244439aa372d90f984082
23:09:39 puppeteer07: Detecting platforms...
23:09:43 puppeteer07: Detected following platforms:
23:09:43 puppeteer07:   nodejs: 12.18.2
23:09:44 puppeteer07: Using intermediate directory '/tmp/8d86b0546c187dd'.
23:09:44 puppeteer07: Copying files to the intermediate directory...
23:09:45 puppeteer07: Done in 1 sec(s).
23:09:45 puppeteer07: Source directory     : /tmp/8d86b0546c187dd
23:09:45 puppeteer07: Destination directory: /tmp/build/expressbuild
23:09:45 puppeteer07: Using Node version:
23:09:45 puppeteer07: v12.18.2
23:09:45 puppeteer07: Using Npm version:
23:09:54 puppeteer07: 6.14.5
23:09:54 puppeteer07: Running 'npm install --unsafe-perm'...
23:10:14 puppeteer07: > puppeteer@5.3.1 install /tmp/8d86b0546c187dd/node_modules/puppeteer
23:10:14 puppeteer07: > node install.js
23:11:13 puppeteer07: Chromium (800071) downloaded to /tmp/8d86b0546c187dd/node_modules/puppeteer/.local-chromium/linux-800071
23:11:14 puppeteer07: npm WARN functions-puppeteer@1.0.0 No description
23:11:14 puppeteer07: added 53 packages from 74 contributors and audited 53 packages in 76.393s
23:11:14 puppeteer07: npm WARN functions-puppeteer@1.0.0 No repository field.
23:11:14 puppeteer07: npm WARN functions-puppeteer@1.0.0 No license field.
23:11:14 puppeteer07: 5 packages are looking for funding
23:11:14 puppeteer07:   run `npm fund` for details
23:11:14 puppeteer07: found 0 vulnerabilities
23:11:14 puppeteer07: Copying files to destination directory '/tmp/build/expressbuild'...
23:12:08 puppeteer07: Done in 54 sec(s).
23:12:09 puppeteer07: Removing existing manifest file
23:12:09 puppeteer07: Creating a manifest file...
23:12:09 puppeteer07: Manifest file created.
23:12:09 puppeteer07: Done in 145 sec(s).
23:12:10 puppeteer07: Writing the artifacts to a Zip file
23:14:06 puppeteer07: Running post deployment command(s)...
23:14:06 puppeteer07: Triggering recycle (preview mode disabled).
23:14:06 puppeteer07: Deployment successful.
23:14:09 puppeteer07: Started postDeployTask "npm install".
23:14:19 puppeteer07: Syncing triggers...
23:15:15 puppeteer07: Syncing triggers (Attempt 2/6)...
23:16:17 puppeteer07: Syncing triggers (Attempt 3/6)...
23:17:28 puppeteer07: Syncing triggers (Attempt 4/6)...
23:18:59 puppeteer07: Syncing triggers (Attempt 5/6)...
23:19:00 puppeteer07: Querying triggers...
23:19:02 puppeteer07: HTTP Trigger Urls:
  screenshot: https://puppeteer07.azurewebsites.net/api/screenshot

**Comment by StannieV** [comment]
Apparently, the application has to be rolled out twice for it to work. It seems that not all files are present the first time. After the first deployment, I got the following error.

After the second deployment, it works well. :S

Error:
Exception while executing function: Functions.screenshot <--- Result: Failure Exception: Worker was unable to load function screenshot: 'Error: Cannot find module' puppeteer 'Require stack: - /home/site/wwwroot/screenshot/index.js - /azure-functions-host/workers/node/worker-bundle.js - /azure-functions-host/workers/node/dist/src/nodejsWorker.js' Stack: Error: Cannot find module 'puppeteer' Require stack: - /home/site/wwwroot/screenshot/index.js - /azure-functions-host/workers/node/worker-bundle.js - /azure-functions-host/workers/node/dist/src/nodejsWorker.js at Function.Module._resolveFilename (internal / modules / cjs / loader.js: 965: 15) at Function.Module._load (internal / modules / cjs / loader.js: 841: 27) at Module.require (internal / modules / cjs / loader.js: 1025: 19) at require (internal / modules / cjs / helpers.js: 72: 18) at Object. <anonymous> (/home/site/wwwroot/screenshot/index.js:1:19 ) at Module._compile (internal / modules / cjs / loader.js: 1137: 30) at Object.Module._extensions..js (internal / modules / cjs / l oader.js: 1157: 10) at Module.load (internal / modules / cjs / loader.js: 985: 32) at Function.Module._load (internal / modules / cjs / loader.js: 878: 14) at Module .require (internal / modules / cjs / loader.js: 1025: 19)

**Comment by StannieV** [comment]
It also works with consumption plan

**Comment by anthonychu** [comment]
Does consumption plan require deploying twice? I haven’t experienced a problem with it yet and I’ve deployed a few apps. Haven’t tested app service plans.

**Comment by StannieV** [comment]
For consumption plans, it was not necessary to deploy twice.

I'm not sure why it is necessary with App Service plan. But this has been my experience and may be useful for others to know.

**Comment by maiajhonathan** [comment]
Anyone having trouble getting it to work when using typescript?
[Error]   Something went wrong and the scheduler was forced to exit.
Details: Error: Could not find Chromium (rev. 1095492). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration

{
  "azureFunctions.deploySubpath": ".",
  // "azureFunctions.postDeployTask": "npm install",
  "azureFunctions.projectLanguage": "TypeScript", (Also tried with JavaScript)
  "azureFunctions.projectRuntime": "~4",
  "debug.internalConsoleOptions": "neverOpen",
  "azureFunctions.scmDoBuildDuringDeployment": true,
  // "azureFunctions.preDeployTask": "npm prune" // tried adding the commented lines as well
}

DEPLOY COMMAND:
func azure functionapp publish report-scheduler-linux --build remote

REMOTE DEPLOY LOGS:
Uploading 58.61 MB [##############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '38c122c2-8'.
PreDeployment: context.CleanOutputPath False
PreDeployment: context.OutputPath /home/site/wwwroot
Repository path is /tmp/zipdeploy/extracted
Running oryx build...
Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version ~14
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210120.1, Commit: 66c7820d7df527aaffabd2563a49ad57930999c9, ReleaseTagName: 20210120.1

Build Operation ID: |1RK3bkY1Ue4=.83ec97b4_
Repository Commit : 38c122c2-8da3-477a-b4a9-efe295e370e8

Detecting platforms...
Detected following platforms:
  nodejs: 14.19.1
  python: 3.8.16
Version '3.8.16' of platform 'python' is not installed. Generating script to install it...


Source directory     : /tmp/zipdeploy/extracted
Destination directory: /home/site/wwwroot


Downloading and extracting 'python' version '3.8.16' to '/tmp/oryx/platforms/python/3.8.16'...
Downloaded in 2 sec(s).
Verifying checksum...
Extracting contents...
Done in 7 sec(s).


Using Node version:
v14.19.1

Using Npm version:
6.14.16

Running 'npm install --unsafe-perm'...

npm WARN report-scheduler-linux@1.0.0 No description
npm WARN report-scheduler-linux@1.0.0 No repository field.
npm WARN report-scheduler-linux@1.0.0 No license field.

up to date in 6.03s

83 packages are looking for funding
  run `npm fund` for details


Running 'npm run build'...


> report-scheduler-linux@1.0.0 build /tmp/zipdeploy/extracted
> ./node_modules/typescript/bin/tsc

Preparing output...

Copying files to destination directory '/home/site/wwwroot'...
Done in 7 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 37 sec(s).
Running post deployment command(s)...

Generating summary of Oryx build
Deployment Log file does not exist in /tmp/oryx-build.log
The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
Triggering recycle (preview mode disabled).
Linux Consumption plan has a 1.5 GB memory limit on a remote build container.
To check our service limit, please visit https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits
Writing the artifacts to a squashfs file
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /home/site/artifacts/functionappartifact.squashfs, block size 131072.

[===========================================================\] 29757/29757 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
        compressed data, compressed metadata, compressed fragments, compressed xattrs
        duplicates are removed
Filesystem size 43216.21 Kbytes (42.20 Mbytes)
        18.36% of uncompressed filesystem size (235366.68 Kbytes)
Inode table size 285454 bytes (278.76 Kbytes)
        27.62% of uncompressed inode table size (1033427 bytes)
Directory table size 291574 bytes (284.74 Kbytes)
        38.96% of uncompressed directory table size (748434 bytes)
Number of duplicate files found 5439
Number of inodes 32135
Number of files 28858
Number of fragments 811
Number of symbolic links  0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 3277
Number of ids (unique uids + gids) 1
Number of uids 1
        root (0)
Number of gids 1
        root (0)
Creating placeholder blob for linux consumption function app...
SCM_RUN_FROM_PACKAGE placeholder blob scm-latest-report-scheduler-linux.zip located
Uploading built content /home/site/artifacts/functionappartifact.squashfs for linux consumption function app...
Resetting all workers for report-scheduler-linux.azurewebsites.net
Deployment successful. deployer = Push-Deployer deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
Remote build succeeded!
Syncing triggers...
Functions in report-scheduler-linux:
    report-scheduler - [timerTrigger]

Anyone facing the same issue?

**Comment by premsagar09** [comment]
I am facing below issue , after deployment 

Result: Failure Exception: Worker was unable to load function screenshot: 'Cannot find module 'puppeteer' Require stack: - C:\home\site\wwwroot\screenshot\index.js - C:\Program Files (x86)\SiteExtensions\Functions\4.28.4\workers\node\dist\src\worker-bundle.js - C:\Program Files (x86)\SiteExtensions\Functions\4.28.4\workers\node\dist\src\nodejsWorker.js' Stack: Error: Worker was unable to load function screenshot: 'Cannot find module 'puppeteer' Require stack: - C:\home\site\wwwroot\screenshot\index.js - C:\Program Files (x86)\SiteExtensions\Functions\4.28.4\workers\node\dist\src\worker-bundle.js - C:\Program Files (x86)\SiteExtensions\Functions\4.28.4\workers\node\dist\src\nodejsWorker.js' at Module._resolveFilename (node:internal/modules/cjs/loader:995:15) at Module._load (node:internal/modules/cjs/loader:841:27) at Module.require (node:internal/modules/cjs/loader:1061:19) at Object.apply (C:\Program Files (x86)\SiteExtensions\Functions\4.28.4\workers\node\dist\src\worker-bundle.js:2:49412) at require (node:internal/modules/cjs/helpers:103:18) at Object.<anonymous> (C:\home\site\wwwroot\screenshot\index.js:1:19) at Module._compile (node:internal/modules/cjs/loader:1159:14) at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) at Module.load (node:internal/modules/cjs/loader:1037:32) at Module._load (node:internal/modules/cjs/loader:878:12)

**Comment by premsagar09** [comment]
This is my index.ts

const puppeteer = require("puppeteer");

module.exports = async function (context, req) {
    try {
        const content = req.query.content || 'MR';
        const browser = await puppeteer.launch({
            headless: "new",
            args: ["--no-sandbox", "--disable-setuid-sandbox"],

        });
        const htmlContent = `<h1>Hello ${content}</h1><p>This is custom HTML content.</p>`;
        const page = await browser.newPage();
        await page.goto("https://www.google.com/");
        // Set HTML content
        await page.setContent(htmlContent);
        // Options for PDF generation
        const options = {
            format: "A4",
        };
        // Generate PDF
        const bufferData = await page.pdf(options);
        // Close the browser
        await browser.close();
        context.res = {
            // body: {
            //     buffer: bufferData
            // },
            body: bufferData,
            // headers: {
            //     "content-type": "im"
            // }
        };
    } catch (error) {
        context.log(error)
        context.res = {
            body: error,
            // headers: {
            //     "content-type": "im"
            // }
        };
    }
};

and configured cache path also, still facing above error 

const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
